spring:
  application:
    name: ns-sf-connector

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

netsuite:
  base_url: ${NS_BASE_URI}
  auth-url: ${NS_TOKEN_URI}
  client-id: ${NS_CLIENT_ID}
  cert-id: ${NS_CERT_ID}
  grant-type: client_credentials
  client-assertion-type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
  scope:
    - restlets
    - rest_webservices
salesforce:
  base_url: ${SF_BASE_URI}
  auth-url: ${SF_TOKEN_URI}
  account-url: ${SF_ACCOUNT_URI}
  client-id: ${SF_CLIENT_ID}
  client-secret: ${SF_CLIENT_SECRET}
  grant-type: client_credentials


